databases:
  - name: airbnbclone
    databaseName: airbnbclone
    user: ffenland
    region: singapore

services:
  - type: web
    name: mysite
    runtime: python
    region: singapore
    buildCommand: "./build.sh"
    startCommand: "gunicorn mysite.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: airbnbclone
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
