# Generated by Django 4.2.2 on 2023-06-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='kind',
            field=models.CharField(choices=[('inddor', '실내'), ('outdoor', '실외'), ('both', '실내외'), ('takeout', '포장전용')], max_length=20),
        ),
    ]
