# Generated by Django 4.2.2 on 2023-06-23 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0002_alter_cafe_kind'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='facility',
            options={'verbose_name_plural': 'Facilities'},
        ),
        migrations.AlterField(
            model_name='cafe',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만든날짜'),
        ),
        migrations.AlterField(
            model_name='cafe',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='변경날짜'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='만든날짜'),
        ),
        migrations.AlterField(
            model_name='facility',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='변경날짜'),
        ),
    ]
