# Generated by Django 4.2.2 on 2023-07-03 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file',
        ),
        migrations.RemoveField(
            model_name='video',
            name='file',
        ),
        migrations.AlterField(
            model_name='photo',
            name='cf_id',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='cf_id',
            field=models.URLField(),
        ),
    ]
