# Generated by Django 4.2.2 on 2023-06-26 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0004_cafe_category'),
        ('experiences', '0002_experience_category'),
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='cafes',
            field=models.ManyToManyField(blank=True, to='cafes.cafe'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='experiences',
            field=models.ManyToManyField(blank=True, to='experiences.experience'),
        ),
    ]
