# Generated by Django 4.2.2 on 2023-07-06 01:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cafes', '0004_cafe_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='만든날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='변경날짜')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('type', models.CharField(choices=[('coffee', '커피'), ('ade', '에이드'), ('tea', '차'), ('bread', '빵'), ('snack', '스낵'), ('dduk', '떡')], max_length=12)),
                ('image', models.URLField(blank=True, null=True)),
                ('cafes', models.ManyToManyField(blank=True, null=True, to='cafes.cafe')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.URLField(blank=True, null=True)),
                ('menus', models.ManyToManyField(blank=True, null=True, to='menus.menu')),
            ],
        ),
    ]
