# Generated by Django 4.2.2 on 2023-07-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='experience_time',
        ),
        migrations.AddField(
            model_name='booking',
            name='exp_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='exp_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
