# Generated by Django 4.2.2 on 2023-07-06 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_remove_booking_experience_time_booking_exp_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='exp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
