# Generated by Django 4.2.2 on 2023-07-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_exp_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='exp_date',
        ),
    ]
