# Generated by Django 4.2.2 on 2023-06-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('addr_sido', models.CharField(max_length=9, verbose_name='시도')),
                ('addr_sgg', models.CharField(max_length=9, verbose_name='시군구')),
                ('addr_umd', models.CharField(max_length=5, verbose_name='읍면동')),
                ('pets_allowed', models.BooleanField(default=False)),
            ],
        ),
    ]
